### ISSUE TITLE
Install Octokit into a Xamarin Studio project

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#283]
As of 0.1.7, we still only ship binaries for `net45` and `netcore45` profiles.

I've got a half-finished PR for doing PCL builds (needs some love) but after switching over to use PCL bits I'd like to expand the build scripts to ensure that we target the right profiles so that MonoTouch and MonoDroid devs can install the same package as .NET devs do.

**TODO:**
- [x] target `Profile78` in Octokit PCL build
- [x] verify NuGet package references Microsoft.Net.Http
- [x] test installing into a Monotouch project and can do a basic operation
- [x] test installing into a Monodroid project and can do a basic operation
- [x] update docs to indicate how to install into Xamarin Studio
