### ISSUE TITLE
Release 0.1.0 Checklist

### ISSUE THREAD

**Issue by haacked** [octokit/octokit.net#78]
Release checklist
### Must have for ship
- [x] Check and change secrets
- [x] Ask @jeejkang about where the Octokit.net illustration is (http://octokit.github.io/)
- [ ] Update GitHub Pages site ([PR is ready to go](https://github.com/octokit/octokit.github.com/pull/6))
- [x] Blog post
### Nice to have
- [x] Private CI while project public (investigate)
- [ ] Public CI (Chat room notifications)
- [ ] Samples
- [ ] Documentation generation
